"""LMS Provider Registry — maps provider strings to adapter instances.

Each adapter implements the LMSProvider Protocol.  New providers are added by:
1. Creating a concrete adapter class
2. Calling register_provider(MyAdapter()) at module bottom

On import this module auto-registers:
  - GoogleClassroomAdapter (delegates to existing /api/google/* flow)
  - BrightspaceAdapter    (full implementation — OAuth + sync, #24/#25)
  - CanvasAdapter          (full implementation — OAuth + sync, Canvas LMS)
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Protocol, runtime_checkable

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Protocol (interface)
# ---------------------------------------------------------------------------


@runtime_checkable
class LMSProvider(Protocol):
    """Interface all LMS adapters must implement."""

    provider_id: str       # "google_classroom" | "brightspace" | "canvas" | ...
    display_name: str      # Human-readable name shown in the UI
    supports_oauth: bool   # Whether OAuth is supported (False = manual token entry)
    requires_institution_url: bool  # True if the user must supply their school's base URL

    def get_auth_url(self, user_id: int, redirect_uri: str) -> str:
        """Return the OAuth authorization URL for this provider.

        Args:
            user_id:      ClassBridge user ID initiating the connection.
            redirect_uri: Where the provider should redirect after consent.

        Returns:
            Absolute URL the frontend should navigate the user to.
        """
        ...

    def exchange_code(self, code: str, redirect_uri: str) -> dict:
        """Exchange an OAuth authorization code for access/refresh tokens.

        Args:
            code:         Authorization code received from the provider.
            redirect_uri: Must match the redirect_uri used in get_auth_url.

        Returns:
            Dict with keys: access_token, refresh_token, expires_at (ISO str).
        """
        ...


# ---------------------------------------------------------------------------
# Concrete adapters
# ---------------------------------------------------------------------------


class GoogleClassroomAdapter:
    """Adapter for the existing Google Classroom integration.

    OAuth is handled by the existing /api/google/* routes.
    This adapter exists purely for provider registry/discovery purposes.
    """

    provider_id = "google_classroom"
    display_name = "Google Classroom"
    supports_oauth = True
    requires_institution_url = False

    def get_auth_url(self, user_id: int, redirect_uri: str) -> str:
        """Delegate to the existing Google OAuth connect endpoint."""
        return f"/api/google/connect?redirect_uri={redirect_uri}"

    def exchange_code(self, code: str, redirect_uri: str) -> dict:
        """Not used — the existing /api/google/callback handles this."""
        raise NotImplementedError(
            "Google Classroom token exchange is handled by the existing "
            "/api/google/callback flow.  Do not call this method directly."
        )


class BrightspaceAdapter:
    """Full adapter for D2L Brightspace — implements LMSProvider (#24/#25).

    OAuth flow is handled by the dedicated endpoints in
    app/api/routes/lms_connections.py (GET /api/lms/brightspace/connect +
    /callback + /refresh).  This adapter is responsible for syncing
    courses, assignments, materials, and grades once a token is available.
    """

    provider_id = "brightspace"
    display_name = "D2L Brightspace"
    supports_oauth = True
    requires_institution_url = True

    def get_auth_url(self, user_id: int, redirect_uri: str) -> str:
        """Return the institution-agnostic connect URL.

        The real OAuth URL (which requires a specific institution's base_url)
        is generated by the /api/lms/brightspace/connect endpoint once the
        user selects their institution.
        """
        return f"/api/lms/brightspace/connect?redirect_uri={redirect_uri}"

    def exchange_code(self, code: str, redirect_uri: str) -> dict:
        """Not used directly — the /api/lms/brightspace/callback endpoint
        handles token exchange using BrightspaceOAuthClient.
        """
        raise NotImplementedError(
            "Brightspace token exchange is handled by the /api/lms/brightspace/callback "
            "endpoint.  Do not call this method directly."
        )

    async def sync_courses(self, connection, db) -> list:
        """Fetch Brightspace enrollments and upsert Course records.

        Args:
            connection: LMSConnection with access_token_enc, institution, etc.
            db:         SQLAlchemy Session.

        Returns:
            List of persisted Course ORM instances.
        """
        from app.services.brightspace import BrightspaceAPIClient
        from app.models.course import Course

        client = self._make_client(connection)
        enrollments = await client.get_courses()
        courses: list = []

        for enrollment in enrollments:
            org_unit = enrollment.get("OrgUnit", enrollment)
            org_unit_id = str(org_unit.get("Id", ""))
            name = org_unit.get("Name", "Untitled Course")
            if not org_unit_id:
                continue

            course = (
                db.query(Course)
                .filter(
                    Course.lms_provider == "brightspace",
                    Course.lms_external_id == org_unit_id,
                )
                .first()
            )
            if course is None:
                course = Course(
                    name=name,
                    lms_provider="brightspace",
                    lms_external_id=org_unit_id,
                    classroom_type="school",
                )
                db.add(course)
                logger.debug("BrightspaceAdapter: created course %s (%s)", name, org_unit_id)
            else:
                course.name = name
                logger.debug("BrightspaceAdapter: updated course %s (%s)", name, org_unit_id)

            courses.append(course)

        db.commit()
        for course in courses:
            db.refresh(course)

        logger.info(
            "BrightspaceAdapter.sync_courses: synced %d courses (connection=%s)",
            len(courses),
            connection.id,
        )
        return courses

    async def sync_assignments(self, connection, db) -> list:
        """Fetch Brightspace dropbox folders and upsert Assignment records.

        Iterates over all courses already synced for this connection's
        institution and fetches dropbox folders for each.

        Args:
            connection: LMSConnection
            db:         SQLAlchemy Session

        Returns:
            List of persisted Assignment ORM instances.
        """
        from app.services.brightspace import BrightspaceAPIClient
        from app.models.course import Course
        from app.models.assignment import Assignment

        client = self._make_client(connection)

        courses = (
            db.query(Course)
            .filter(Course.lms_provider == "brightspace")
            .all()
        )
        assignments: list = []

        for course in courses:
            course_id = course.lms_external_id
            if not course_id:
                continue

            try:
                folders = await client.get_assignments(course_id)
            except Exception as exc:
                logger.warning(
                    "BrightspaceAdapter: failed to fetch assignments for "
                    "course %s: %s",
                    course_id,
                    exc,
                )
                continue

            for folder in folders:
                folder_id = str(folder.get("Id", ""))
                title = folder.get("Name", "Untitled Assignment")
                if not folder_id:
                    continue

                due_date = self._parse_completion_date(folder.get("CompletionDate"))

                assignment = (
                    db.query(Assignment)
                    .filter(
                        Assignment.lms_provider == "brightspace",
                        Assignment.lms_external_id == folder_id,
                    )
                    .first()
                )
                if assignment is None:
                    assignment = Assignment(
                        title=title,
                        course_id=course.id,
                        lms_provider="brightspace",
                        lms_external_id=folder_id,
                        due_date=due_date,
                    )
                    db.add(assignment)
                else:
                    assignment.title = title
                    assignment.due_date = due_date

                assignments.append(assignment)

        db.commit()
        for a in assignments:
            db.refresh(a)

        logger.info(
            "BrightspaceAdapter.sync_assignments: synced %d assignments (connection=%s)",
            len(assignments),
            connection.id,
        )
        return assignments

    async def sync_materials(self, connection, db) -> list:
        """Fetch Brightspace content TOC and upsert CourseContent records.

        Flattens module trees to individual topic/content items.

        Args:
            connection: LMSConnection
            db:         SQLAlchemy Session

        Returns:
            List of persisted CourseContent ORM instances.
        """
        from app.services.brightspace import BrightspaceAPIClient
        from app.models.course import Course
        from app.models.course_content import CourseContent

        client = self._make_client(connection)

        courses = (
            db.query(Course)
            .filter(Course.lms_provider == "brightspace")
            .all()
        )
        materials: list = []

        for course in courses:
            course_id = course.lms_external_id
            if not course_id:
                continue

            try:
                modules = await client.get_course_content(course_id)
            except Exception as exc:
                logger.warning(
                    "BrightspaceAdapter: failed to fetch content for course %s: %s",
                    course_id,
                    exc,
                )
                continue

            topics = self._flatten_modules(modules)
            for topic in topics:
                topic_id = str(topic.get("Id", ""))
                title = topic.get("Title", "Untitled Material")
                if not topic_id:
                    continue

                url = topic.get("Url") or topic.get("ExternalUrl", "")
                content_type = self._detect_content_type(topic)

                content = (
                    db.query(CourseContent)
                    .filter(
                        CourseContent.lms_provider == "brightspace",
                        CourseContent.lms_external_id == topic_id,
                    )
                    .first()
                )
                if content is None:
                    content = CourseContent(
                        course_id=course.id,
                        title=title,
                        reference_url=url or None,
                        content_type=content_type,
                        lms_provider="brightspace",
                        lms_external_id=topic_id,
                    )
                    db.add(content)
                else:
                    content.title = title
                    content.reference_url = url or None

                materials.append(content)

        db.commit()
        for m in materials:
            db.refresh(m)

        logger.info(
            "BrightspaceAdapter.sync_materials: synced %d materials (connection=%s)",
            len(materials),
            connection.id,
        )
        return materials

    async def sync_grades(self, connection, db) -> None:
        """Fetch Brightspace final grades and update matched Assignment records.

        For each Brightspace course, fetches final grade values and attempts
        to match them to existing Assignment records by lms_external_id.

        Args:
            connection: LMSConnection
            db:         SQLAlchemy Session
        """
        from app.services.brightspace import BrightspaceAPIClient
        from app.models.course import Course
        from app.models.assignment import Assignment

        client = self._make_client(connection)

        courses = (
            db.query(Course)
            .filter(Course.lms_provider == "brightspace")
            .all()
        )

        for course in courses:
            course_id = course.lms_external_id
            if not course_id:
                continue

            try:
                grade_entries = await client.get_grades(course_id)
            except Exception as exc:
                logger.warning(
                    "BrightspaceAdapter: failed to fetch grades for course %s: %s",
                    course_id,
                    exc,
                )
                continue

            for entry in grade_entries:
                grade_object_id = str(entry.get("GradeObjectId", ""))
                points_earned = entry.get("PointsNumerator")
                if not grade_object_id or points_earned is None:
                    continue

                assignment = (
                    db.query(Assignment)
                    .filter(
                        Assignment.lms_provider == "brightspace",
                        Assignment.lms_external_id == grade_object_id,
                    )
                    .first()
                )
                if assignment:
                    try:
                        assignment.max_points = float(points_earned)
                    except (TypeError, ValueError):
                        pass

        db.commit()
        logger.info(
            "BrightspaceAdapter.sync_grades: completed for connection=%s",
            connection.id,
        )

    # ── Private helpers ──────────────────────────────────────────────────

    @staticmethod
    def _make_client(connection) -> "BrightspaceAPIClient":  # noqa: F821
        """Construct a BrightspaceAPIClient from a connection record."""
        from app.services.brightspace import BrightspaceAPIClient

        base_url = ""
        if connection.institution and connection.institution.base_url:
            base_url = connection.institution.base_url

        token = connection.access_token_enc or ""
        return BrightspaceAPIClient(base_url=base_url, access_token=token)

    @staticmethod
    def _parse_completion_date(raw: str | None) -> datetime | None:
        """Parse an ISO 8601 date string into a timezone-aware datetime."""
        if not raw:
            return None
        try:
            # Try fromisoformat first (Python 3.11+ handles Z suffix; older does not)
            cleaned = raw.replace("Z", "+00:00")
            return datetime.fromisoformat(cleaned)
        except (ValueError, AttributeError):
            return None

    @staticmethod
    def _flatten_modules(modules: list[dict]) -> list[dict]:
        """Recursively flatten a Brightspace TOC module tree to leaf topics."""
        topics: list[dict] = []
        for module in modules:
            topics.extend(module.get("Topics", []))
            child_modules = module.get("Modules", [])
            if child_modules:
                topics.extend(BrightspaceAdapter._flatten_modules(child_modules))
        return topics

    @staticmethod
    def _detect_content_type(topic: dict) -> str:
        """Classify a topic into a CourseContent content_type string.

        Heuristics:
          - TypeIdentifier == "Link" or ExternalUrl present → "resources"
          - Url ending in .pdf                              → "notes"
          - Default                                         → "other"
        """
        type_id = topic.get("TypeIdentifier", "")
        url = topic.get("Url", "") or topic.get("ExternalUrl", "")

        if type_id == "Link" or (url and not url.startswith("/content")):
            return "resources"
        if url and url.lower().endswith(".pdf"):
            return "notes"
        return "other"


class CanvasAdapter:
    """Full adapter for Instructure Canvas LMS.

    OAuth flow is handled by the dedicated endpoints in
    app/api/routes/lms_connections.py (GET /api/lms/canvas/connect +
    /callback + /refresh).  This adapter is responsible for syncing
    courses, assignments, materials, and grades once a token is available.
    """

    provider_id = "canvas"
    display_name = "Canvas LMS"
    supports_oauth = True
    requires_institution_url = True

    def get_auth_url(self, user_id: int, redirect_uri: str) -> str:
        """Return the institution-agnostic connect URL.

        The real OAuth URL (which requires a specific institution's base_url)
        is generated by the /api/lms/canvas/connect endpoint once the
        user selects their institution.
        """
        return f"/api/lms/canvas/connect?redirect_uri={redirect_uri}"

    def exchange_code(self, code: str, redirect_uri: str) -> dict:
        """Not used directly — the /api/lms/canvas/callback endpoint
        handles token exchange using CanvasOAuthClient.
        """
        raise NotImplementedError(
            "Canvas token exchange is handled by the /api/lms/canvas/callback "
            "endpoint.  Do not call this method directly."
        )

    async def sync_courses(self, connection, db) -> list:
        """Fetch Canvas courses and upsert Course records.

        Tries enrollment_type=student first; falls back to teacher for
        teacher accounts.  Uses lms_provider="canvas" and lms_external_id
        set to the string representation of the Canvas course ID.

        Args:
            connection: LMSConnection with access_token_enc, institution, etc.
            db:         SQLAlchemy Session.

        Returns:
            List of persisted Course ORM instances.
        """
        from app.models.course import Course

        client = self._make_client(connection)
        # Try student enrollment first; if empty, try teacher
        canvas_courses = await client.get_courses(enrollment_type="student")
        if not canvas_courses:
            canvas_courses = await client.get_courses(enrollment_type="teacher")

        courses: list = []

        for canvas_course in canvas_courses:
            course_id = str(canvas_course.get("id", ""))
            name = canvas_course.get("name", "Untitled Course")
            course_code = canvas_course.get("course_code", "")
            sis_course_id = canvas_course.get("sis_course_id")
            description = canvas_course.get("public_description") or canvas_course.get("description", "")

            if not course_id:
                continue

            course = (
                db.query(Course)
                .filter(
                    Course.lms_provider == "canvas",
                    Course.lms_external_id == course_id,
                )
                .first()
            )
            if course is None:
                course = Course(
                    name=name,
                    description=description or None,
                    subject_code=course_code or None,
                    lms_provider="canvas",
                    lms_external_id=course_id,
                    classroom_type="school",
                )
                db.add(course)
                logger.debug("CanvasAdapter: created course %s (%s)", name, course_id)
            else:
                course.name = name
                if description:
                    course.description = description
                if course_code:
                    course.subject_code = course_code
                logger.debug("CanvasAdapter: updated course %s (%s)", name, course_id)

            courses.append(course)

        db.commit()
        for course in courses:
            db.refresh(course)

        logger.info(
            "CanvasAdapter.sync_courses: synced %d courses (connection=%s)",
            len(courses),
            connection.id,
        )
        return courses

    async def sync_assignments(self, connection, db) -> list:
        """Fetch Canvas assignments and upsert Assignment records.

        Iterates over all Canvas courses already synced for this connection
        and fetches assignments for each.  Maps:
          - due_at           → due_date (ISO 8601 parse)
          - points_possible  → max_points
          - name             → title

        Args:
            connection: LMSConnection
            db:         SQLAlchemy Session

        Returns:
            List of persisted Assignment ORM instances.
        """
        from app.models.course import Course
        from app.models.assignment import Assignment

        client = self._make_client(connection)

        courses = (
            db.query(Course)
            .filter(Course.lms_provider == "canvas")
            .all()
        )
        assignments: list = []

        for course in courses:
            canvas_course_id = course.lms_external_id
            if not canvas_course_id:
                continue

            try:
                canvas_assignments = await client.get_assignments(canvas_course_id)
            except Exception as exc:
                logger.warning(
                    "CanvasAdapter: failed to fetch assignments for course %s: %s",
                    canvas_course_id,
                    exc,
                )
                continue

            for canvas_assignment in canvas_assignments:
                assignment_id = str(canvas_assignment.get("id", ""))
                title = canvas_assignment.get("name", "Untitled Assignment")
                if not assignment_id:
                    continue

                due_date = self._parse_iso_date(canvas_assignment.get("due_at"))
                points_possible = canvas_assignment.get("points_possible")
                try:
                    max_points = float(points_possible) if points_possible is not None else None
                except (TypeError, ValueError):
                    max_points = None

                assignment = (
                    db.query(Assignment)
                    .filter(
                        Assignment.lms_provider == "canvas",
                        Assignment.lms_external_id == assignment_id,
                    )
                    .first()
                )
                if assignment is None:
                    assignment = Assignment(
                        title=title,
                        course_id=course.id,
                        lms_provider="canvas",
                        lms_external_id=assignment_id,
                        due_date=due_date,
                        max_points=max_points,
                    )
                    db.add(assignment)
                else:
                    assignment.title = title
                    assignment.due_date = due_date
                    if max_points is not None:
                        assignment.max_points = max_points

                assignments.append(assignment)

        db.commit()
        for a in assignments:
            db.refresh(a)

        logger.info(
            "CanvasAdapter.sync_assignments: synced %d assignments (connection=%s)",
            len(assignments),
            connection.id,
        )
        return assignments

    async def sync_materials(self, connection, db) -> list:
        """Fetch Canvas modules + items and upsert CourseContent records.

        Module item type mapping:
          - "File"        → content_type="document"
          - "ExternalUrl" → content_type="resources"
          - "Page"        → content_type="notes"
          - Other         → content_type="other"

        Args:
            connection: LMSConnection
            db:         SQLAlchemy Session

        Returns:
            List of persisted CourseContent ORM instances.
        """
        from app.models.course import Course
        from app.models.course_content import CourseContent

        client = self._make_client(connection)

        courses = (
            db.query(Course)
            .filter(Course.lms_provider == "canvas")
            .all()
        )
        materials: list = []

        for course in courses:
            canvas_course_id = course.lms_external_id
            if not canvas_course_id:
                continue

            try:
                modules = await client.get_course_modules(canvas_course_id)
            except Exception as exc:
                logger.warning(
                    "CanvasAdapter: failed to fetch modules for course %s: %s",
                    canvas_course_id,
                    exc,
                )
                continue

            for module in modules:
                module_items = module.get("items", [])
                for item in module_items:
                    item_id = str(item.get("id", ""))
                    title = item.get("title", "Untitled Material")
                    if not item_id:
                        continue

                    item_type = item.get("type", "")
                    url = item.get("url") or item.get("external_url", "")
                    content_type = self._map_item_type(item_type)

                    content = (
                        db.query(CourseContent)
                        .filter(
                            CourseContent.lms_provider == "canvas",
                            CourseContent.lms_external_id == item_id,
                        )
                        .first()
                    )
                    if content is None:
                        content = CourseContent(
                            course_id=course.id,
                            title=title,
                            reference_url=url or None,
                            content_type=content_type,
                            lms_provider="canvas",
                            lms_external_id=item_id,
                        )
                        db.add(content)
                    else:
                        content.title = title
                        content.reference_url = url or None

                    materials.append(content)

        db.commit()
        for m in materials:
            db.refresh(m)

        logger.info(
            "CanvasAdapter.sync_materials: synced %d materials (connection=%s)",
            len(materials),
            connection.id,
        )
        return materials

    async def sync_grades(self, connection, db) -> None:
        """Fetch Canvas grades and update matched Assignment records.

        For each Canvas course, fetches the grade summary and attempts to
        update Assignment records matched by course via lms_external_id.

        Args:
            connection: LMSConnection
            db:         SQLAlchemy Session
        """
        from app.models.course import Course
        from app.models.assignment import Assignment

        client = self._make_client(connection)

        courses = (
            db.query(Course)
            .filter(Course.lms_provider == "canvas")
            .all()
        )

        for course in courses:
            canvas_course_id = course.lms_external_id
            if not canvas_course_id:
                continue

            try:
                grades = await client.get_grades(canvas_course_id)
            except Exception as exc:
                logger.warning(
                    "CanvasAdapter: failed to fetch grades for course %s: %s",
                    canvas_course_id,
                    exc,
                )
                continue

            # Canvas grades endpoint returns a summary dict (not per-assignment).
            # We store current_score on all assignments in the course as a proxy.
            current_score = grades.get("current_score")
            if current_score is None:
                continue

            try:
                score_value = float(current_score)
            except (TypeError, ValueError):
                continue

            # Update all assignments in the course that don't already have a grade
            course_assignments = (
                db.query(Assignment)
                .filter(
                    Assignment.course_id == course.id,
                    Assignment.lms_provider == "canvas",
                    Assignment.grade.is_(None),
                )
                .all()
            )
            for assignment in course_assignments:
                assignment.grade = str(score_value)

        db.commit()
        logger.info(
            "CanvasAdapter.sync_grades: completed for connection=%s",
            connection.id,
        )

    # ── Private helpers ──────────────────────────────────────────────────

    @staticmethod
    def _make_client(connection) -> "CanvasAPIClient":  # noqa: F821
        """Construct a CanvasAPIClient from a connection record."""
        from app.services.canvas import CanvasAPIClient

        base_url = ""
        if connection.institution and connection.institution.base_url:
            base_url = connection.institution.base_url

        token = connection.access_token_enc or ""
        return CanvasAPIClient(base_url=base_url, access_token=token)

    @staticmethod
    def _parse_iso_date(raw: str | None) -> "datetime | None":
        """Parse a Canvas ISO 8601 date string into a timezone-aware datetime."""
        if not raw:
            return None
        try:
            cleaned = raw.replace("Z", "+00:00")
            return datetime.fromisoformat(cleaned)
        except (ValueError, AttributeError):
            return None

    @staticmethod
    def _map_item_type(item_type: str) -> str:
        """Map a Canvas module item type to a CourseContent content_type string.

        Canvas item types:
          "File"        → "document"
          "ExternalUrl" → "resources"
          "Page"        → "notes"
          Other         → "other"
        """
        mapping = {
            "File": "document",
            "ExternalUrl": "resources",
            "Page": "notes",
        }
        return mapping.get(item_type, "other")


# ---------------------------------------------------------------------------
# Registry helpers
# ---------------------------------------------------------------------------

_REGISTRY: dict[str, LMSProvider] = {}


def register_provider(adapter: LMSProvider) -> None:
    """Add (or replace) a provider in the global registry."""
    _REGISTRY[adapter.provider_id] = adapter


def get_provider(provider_id: str) -> LMSProvider | None:
    """Look up a provider by its string ID.  Returns None if not found."""
    return _REGISTRY.get(provider_id)


def list_providers() -> list[dict]:
    """Return a serializable list of all registered providers."""
    return [
        {
            "provider_id": p.provider_id,
            "display_name": p.display_name,
            "supports_oauth": p.supports_oauth,
            "requires_institution_url": p.requires_institution_url,
        }
        for p in _REGISTRY.values()
    ]


# ---------------------------------------------------------------------------
# Auto-register all built-in providers on import
# ---------------------------------------------------------------------------

register_provider(GoogleClassroomAdapter())
register_provider(BrightspaceAdapter())
register_provider(CanvasAdapter())
