"""CB-CMCP-001 M3-C 3C-4 (#4587) — Bridge "What [child] is learning" card backend.

Surfaces APPROVED + SELF_STUDY CMCP artifacts to a parent for a single linked
child via ``GET /api/bridge/cards/cmcp/{kid_id}``.

Visibility
----------
- Caller must be PARENT or ADMIN.
- ADMIN sees every linked-child's artifacts unconditionally.
- PARENT must be linked to ``kid_id`` (where ``kid_id`` is a
  ``students.id``) via ``parent_students``. A PARENT calling for a kid
  they are not linked to gets ``404`` so we don't leak whether the row
  exists. This mirrors the no-existence-oracle convention used by the
  M3α parent-companion + review surfaces.

Source of truth
---------------
We read directly from ``study_guides`` rather than the dispatcher's
``bridge_cards`` table (M3-C 3C-1, sibling stripe). M3α renders raw
artifact rows; M3β can layer materialization caching on top of the
dispatcher writes when needed.

Filtering
---------
- ``state IN ('APPROVED', 'SELF_STUDY')`` — these are the two terminal
  states FR-02.6 + D3=C consider parent-visible.
- ``archived_at IS NULL`` — exclude tombstoned rows.
- ``user_id == <kid's User row id>`` — APPROVED rows are pinned to the
  student's User row (artifact_persistence stamps ``user_id`` to the
  generation requester, which is the kid for student-persona).
- For SELF_STUDY rows generated by the parent on behalf of the kid we
  also include rows where ``user_id == parent.id`` AND the artifact is
  parent-persona (``requested_persona == 'parent'``). The link is
  loose — parent-persona artifacts don't carry a kid foreign key — so
  M3α surfaces every parent-self-generated parent-persona row to the
  parent across all their linked kids. M3β can tighten the link with a
  ``shared_with_user_id`` join when product confirms the cardinality.

Response
--------
List of up to 5 items, newest first by ``created_at`` desc:

.. code-block:: json

   {
     "items": [
       {
         "artifact_id": 12,
         "content_type": "study_guide",
         "subject": "Math",
         "topic": "Cell Division",
         "state": "APPROVED",
         "created_at": "2026-04-29T12:00:00+00:00",
         "parent_companion_available": false
       }
     ]
   }

``parent_companion_available`` is ``true`` when the row's persona is
``parent`` AND ``parent_summary`` is non-empty. The frontend uses it to
choose the deep-link target (parent companion page vs generic detail).
"""
from __future__ import annotations

import logging
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, Path, Query
from pydantic import BaseModel, ConfigDict, Field
from sqlalchemy.orm import Session

from app.api.routes.curriculum import require_cmcp_enabled
from app.db.database import get_db
from app.models.course import Course
from app.models.student import Student, parent_students
from app.models.study_guide import StudyGuide
from app.models.user import User, UserRole
from app.services.cmcp.artifact_state import ArtifactState

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/bridge/cards", tags=["Bridge CMCP Cards"])


# ---------------------------------------------------------------------------
# Response schemas
# ---------------------------------------------------------------------------


class BridgeCmcpCardItem(BaseModel):
    """Compact CMCP-artifact row shape rendered on the Bridge card."""

    model_config = ConfigDict(extra="forbid")

    artifact_id: int
    content_type: str
    subject: str | None = None
    topic: str
    state: str
    created_at: str | None = None
    parent_companion_available: bool


class BridgeCmcpCardResponse(BaseModel):
    """List response for ``GET /api/bridge/cards/cmcp/{kid_id}``."""

    model_config = ConfigDict(extra="forbid")

    items: list[BridgeCmcpCardItem] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Visibility helpers
# ---------------------------------------------------------------------------


def _resolve_kid_user_id(db: Session, kid_id: int) -> int | None:
    """Return the kid's ``users.id`` for a given ``students.id``.

    Returns ``None`` when the student row does not exist. Callers map a
    ``None`` return to a 404 — we do not differentiate "no row" from
    "no link" so a parent can't probe for kid existence by id.
    """
    row = db.query(Student.user_id).filter(Student.id == kid_id).first()
    if row is None:
        return None
    return row[0]


def _parent_linked_to_kid(db: Session, parent_user_id: int, kid_id: int) -> bool:
    """True iff the caller PARENT is linked to ``kid_id`` via ``parent_students``."""
    link = (
        db.query(parent_students.c.id)
        .filter(
            parent_students.c.parent_id == parent_user_id,
            parent_students.c.student_id == kid_id,
        )
        .first()
    )
    return link is not None


def _require_parent_or_admin(
    current_user: User = Depends(require_cmcp_enabled),
) -> User:
    """403 unless the caller is PARENT or ADMIN.

    ``require_cmcp_enabled`` resolves the auth + flag gate first, so an
    unauth request → 401, flag-off → 403. Layered with role-allowlist
    here so a TEACHER/STUDENT/etc. authenticated user → 403 too.
    """
    if not (
        current_user.has_role(UserRole.PARENT)
        or current_user.has_role(UserRole.ADMIN)
    ):
        raise HTTPException(
            status_code=403,
            detail="Insufficient permissions for Bridge CMCP card",
        )
    return current_user


# ---------------------------------------------------------------------------
# Serializer
# ---------------------------------------------------------------------------


def _iso(value: Any) -> str | None:
    if value is None:
        return None
    iso = getattr(value, "isoformat", None)
    if callable(iso):
        return iso()
    return str(value)


def _subject_for(row: StudyGuide, course_subject: str | None) -> str | None:
    """Best-effort subject string for the card chip.

    Priority:
      1. ``courses.subject`` when the artifact is course-pinned and the
         join hit a non-empty value (most accurate — matches what the
         parent already sees on the class roster).
      2. The first SE code's subject prefix (Ontario SE codes are
         namespaced ``<SUBJECT>.<...>``) — graceful fallback for SELF_STUDY
         and other course-less rows.
      3. ``None`` — the frontend renders a "—" placeholder.
    """
    if course_subject:
        return course_subject
    if row.se_codes:
        try:
            first = row.se_codes[0]
        except (IndexError, TypeError):
            first = None
        if isinstance(first, str) and first:
            if "." in first:
                return first.split(".", 1)[0]
            return first
    return None


def _to_card_item(
    row: StudyGuide, course_subject: str | None
) -> BridgeCmcpCardItem:
    has_summary = bool(row.parent_summary and row.parent_summary.strip())
    is_parent_persona = row.requested_persona == "parent"
    return BridgeCmcpCardItem(
        artifact_id=row.id,
        content_type=row.guide_type,
        subject=_subject_for(row, course_subject),
        topic=row.title,
        state=row.state,
        created_at=_iso(row.created_at),
        parent_companion_available=is_parent_persona and has_summary,
    )


# ---------------------------------------------------------------------------
# Endpoint
# ---------------------------------------------------------------------------


_VISIBLE_STATES: frozenset[str] = frozenset(
    {ArtifactState.APPROVED, ArtifactState.SELF_STUDY}
)


@router.get(
    "/cmcp/{kid_id}",
    response_model=BridgeCmcpCardResponse,
)
def get_bridge_cmcp_card(
    kid_id: int = Path(..., ge=1),
    limit: int = Query(5, ge=1, le=20),
    current_user: User = Depends(_require_parent_or_admin),
    db: Session = Depends(get_db),
) -> BridgeCmcpCardResponse:
    """Return up to ``limit`` recent APPROVED + SELF_STUDY artifacts for a kid.

    Auth: PARENT or ADMIN (gated by ``_require_parent_or_admin`` +
    ``require_cmcp_enabled``).

    Visibility: PARENT must be linked to ``kid_id`` — otherwise 404 to
    avoid leaking kid existence. ADMIN bypasses the link check.

    Ordering: ``created_at DESC, id DESC``. Default ``limit=5`` matches
    the issue spec; capped at 20 for safety.
    """
    kid_user_id = _resolve_kid_user_id(db, kid_id)
    if kid_user_id is None:
        raise HTTPException(
            status_code=404, detail=f"Kid {kid_id} not found"
        )

    is_admin = current_user.has_role(UserRole.ADMIN)
    if not is_admin:
        if not _parent_linked_to_kid(db, current_user.id, kid_id):
            raise HTTPException(
                status_code=404, detail=f"Kid {kid_id} not found"
            )

    # Build the kid-visibility filter:
    # - APPROVED + SELF_STUDY rows whose ``user_id`` is the kid's User row.
    # - Plus parent-persona SELF_STUDY rows the caller (parent) generated
    #   for themselves — those don't carry a kid foreign key so we
    #   include any parent-persona row owned by the calling parent. (M3α
    #   widens here; M3β can tighten via ``shared_with_user_id`` once the
    #   linking story is finalised — see module docstring.)
    from sqlalchemy import and_, or_

    kid_filter = and_(
        StudyGuide.user_id == kid_user_id,
        StudyGuide.state.in_(_VISIBLE_STATES),
    )

    if is_admin:
        # ADMIN sees the kid's rows; the parent-self-authored
        # SELF_STUDY parent-persona widening is parent-scoped, so
        # don't expand for ADMIN.
        where = kid_filter
    else:
        parent_self_filter = and_(
            StudyGuide.user_id == current_user.id,
            StudyGuide.requested_persona == "parent",
            StudyGuide.state == ArtifactState.SELF_STUDY,
        )
        where = or_(kid_filter, parent_self_filter)

    rows = (
        db.query(StudyGuide, Course.subject)
        .outerjoin(Course, Course.id == StudyGuide.course_id)
        .filter(where)
        .filter(StudyGuide.archived_at.is_(None))
        .order_by(StudyGuide.created_at.desc(), StudyGuide.id.desc())
        .limit(limit)
        .all()
    )

    items = [_to_card_item(r[0], r[1]) for r in rows]

    logger.info(
        "bridge.cards.cmcp.list kid_id=%s caller_id=%s count=%d",
        kid_id,
        current_user.id,
        len(items),
        extra={
            "event": "bridge.cards.cmcp.list",
            "kid_id": kid_id,
            "caller_id": current_user.id,
            "count": len(items),
        },
    )

    return BridgeCmcpCardResponse(items=items)


__all__ = ["router"]
